# Generated by Django 3.2.16 on 2022-12-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='date_downloaded',
            field=models.CharField(max_length=200),
        ),
    ]
