# Generated by Django 3.2.16 on 2022-12-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sw_characters', '0002_alter_csvfile_date_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='file_location',
        ),
    ]
